title: Abe
email: paulo.alfredo.barros@gmail.com
description: >-   
  Hello and welcome Stranger, to the place where my thoughts rest.
resumee: >-
  Paulo Alfredo Barros (A.K.A Abe), 21, FullStack Dev, Musitian, little affair with
  comics and drawing, human father of a simpatic cat called Kernel and world explorer.
baseurl: "" 
url: "" 
twitter_username: abekroenem
github_username:  abekroenem

markdown: kramdown
plugins:
  - jekyll-feed